# Generated by Django 4.0.1 on 2022-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
