# Generated by Django 4.0.1 on 2022-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
