# Generated by Django 4.0.1 on 2022-03-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_archivecour_cour_alter_archiveuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivecour',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour', to='api_app.cour'),
        ),
        migrations.AlterField(
            model_name='archiveuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='archivecour',
            unique_together={('cour',)},
        ),
        migrations.AlterUniqueTogether(
            name='archiveuser',
            unique_together={('user',)},
        ),
    ]
