# Generated by Django 4.0.1 on 2022-03-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_cour_status_alter_archivecour_cour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecour',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.cour'),
        ),
    ]
