# Generated by Django 4.0.1 on 2022-03-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_archivecour_cour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivecour',
            name='cour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cour', to='api_app.cour'),
        ),
    ]
