# Generated by Django 4.0.1 on 2022-03-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_archivecour_cour'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archiveuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archive',
            field=models.BooleanField(),
        ),
    ]
