# Generated by Django 4.0.1 on 2022-04-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_archiveuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archiveuser',
            unique_together={('user',)},
        ),
    ]
